s="Tops Technologies"

print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.center(40,"*"))
print(s.count("Tops"))
print(s.endswith("ese"))
print(s.startswith("to"))
print(len(s))
print(min(s))
print(max(s))
print(s.find("log"))
print(s.index("T",2))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops 123".isalnum())
print("tops1".isalpha())
print("123".isdigit())
print("tops".islower())
print("TOPS".isupper())
print("Hello".replace("l","w"))
print(s.swapcase())


